name: babylai
description: "A Flutter package that provides integration with BabylAI chat functionality, supporting multiple themes and languages."
version: 0.0.2

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get_it: ^8.0.3
  json_serializable: ^6.9.0
  mobx: ^2.5.0
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  signalr_netcore: ^1.4.0
  event_bus: ^2.0.1
  flutter_mobx: ^2.3.0
  pretty_dio_logger: ^1.4.0
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.0
  flutter_markdown: ^0.7.4+3
  logging: ^1.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  no_screenshot: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mobx_codegen: ^2.0.0
  flutter_gen_runner: ^5.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/svg/
    - lib/assets/lottie/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true


  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
